name: template

services:
  ui_web:
    # profiles: ["disabled"] # Uncomment to turn off
    build:
      context: ./ui_web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./ui_web/code:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_HOST_IP=192.168.1.164

