name: template

services:
  ui_web:
  # profiles: ["disabled"] # Uncomment to turn off
    build:
      context: ./ui_web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./ui_web/code:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - api

  ui_mobile:
    # profiles: ["disabled"] # Uncomment to turn off
    build:
      context: ./ui_mobile
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
      - "3001:8081" # Map host 3001 to Metro port for web preview
    volumes:
      - ./ui_mobile/code:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - api

  api:
    # profiles: ["disabled"] # Uncomment to turn off
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888"
    volumes:
      - ./api/code:/app/code
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    # profiles: ["disabled"] # Uncomment to turn off
    build:
      context: ./db_postgres
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres/data:/var/lib/postgresql/data

  db_mgr:
    # profiles: ["disabled"] # Uncomment to turn off
    build:
      context: ./db_postgres_mgr
      dockerfile: Dockerfile.dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:5050"
    depends_on:
      - db
