name: template

services:
  ui_web:
    build:
      context: ./ui_web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./ui_web/code:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888"
    volumes:
      - ./api/code:/app/code
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

